title: Cyseum 2024
author: João Neto
email: joao@neto.pt
description: >- 
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere nisi sem, sit amet bibendum elit placerat id. Quisque eu diam ac turpis gravida facilisis. Nulla vitae ante eget purus fermentum mattis non vitae enim. Etiam odio mauris, lacinia sit amet faucibus sed, dapibus a mi. Suspendisse tristique ante dictum tincidunt hendrerit. Integer vel bibendum lacus. Aenean ullamcorper, elit vitae molestie facilisis, nisl tortor venenatis enim, in efficitur leo justo nec diam. Sed placerat neque id lacus condimentum luctus. Nullam vitae diam ullamcorper dolor vehicula sodales ac ac augue. Morbi quam massa, mattis et mauris vel, commodo congue metus. Donec ut ante eu nunc mollis semper. In eleifend nisi nec porta viverra.
  Fusce commodo mauris imperdiet vestibulum cursus. Integer massa diam, rutrum sit amet pellentesque vel, tincidunt in mi. Nam suscipit volutpat leo ac venenatis. Suspendisse porttitor bibendum enim, vitae tincidunt odio dictum id. Nullam orci justo, dictum a dolor sed, aliquet dignissim sem. Phasellus eros erat, iaculis quis enim at, elementum lacinia ex. Sed vel massa pellentesque nisi ultricies porta sed ac dui. Duis mattis lobortis orci, vitae lobortis nulla eleifend nec. Nullam at ornare tellus. Morbi accumsan, sapien nec lacinia faucibus, neque elit varius sapien, ac dictum dui leo et lacus. Donec aliquam lacinia justo in consectetur. Donec dapibus velit tortor, quis interdum quam aliquet et. Ut id metus libero. Integer rutrum ornare aliquam.

social:
  twitter: joaomlneto
  facebook: joaomlneto
  instagram: joaomlneto
  github: joaomlneto
  linkedin:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true
